// This file is generated by `php artisan lattice:typescript`. Do not edit.
declare module "@lattice-php/core" {
    interface ComponentProps {
        "auth.passkey-verify": {
            label: string | null;
            loadingLabel: string | null;
            optionsUrl: string;
            separator: string | null;
            submitUrl: string;
        };
        "settings.passkey-registration": Record<string, never>;
    }
}

export {};
